//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_OOP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Inq_helperEntities2 : DbContext
    {
        public Inq_helperEntities2()
            : base("name=Inq_helperEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CREATURE_DICTIONARY> CREATURE_DICTIONARY { get; set; }
        public virtual DbSet<GUILD> GUILD { get; set; }
        public virtual DbSet<TASK> TASK { get; set; }
        public virtual DbSet<TASK_CREATURES> TASK_CREATURES { get; set; }
        public virtual DbSet<TASK_MEMBER> TASK_MEMBER { get; set; }
        public virtual DbSet<USER_ARSENAL> USER_ARSENAL { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<WEAPON_DICTIONARY> WEAPON_DICTIONARY { get; set; }
    }
}
