//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_MEMBER
    {
        public int ENTRY_ID { get; set; }
        public Nullable<int> TASK_USER_ID { get; set; }
        public Nullable<int> TASK_ID { get; set; }
        public decimal TASK_USER_PROFIT { get; set; }
    
        public virtual TASK TASK { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
