//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ARSENAL
    {
        public int ENTRY_ID { get; set; }
        public Nullable<int> US_ID { get; set; }
        public Nullable<int> WEAPON_ID { get; set; }
    
        public virtual USERS USERS { get; set; }
        public virtual WEAPON_DICTIONARY WEAPON_DICTIONARY { get; set; }
    }
}
