//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_OOP
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.TASK_MEMBER = new HashSet<TASK_MEMBER>();
            this.USER_ARSENAL = new HashSet<USER_ARSENAL>();
        }


        private string us_TYPE_NAME;

        public Color US_COLOR { get; set; }
        public int US_ID { get; set; }
        public string US_NAME { get; set; }
        public string US_TYPE_NAME
        {
            get
            {
                return us_TYPE_NAME;
            }
            set
            {
                us_TYPE_NAME = value;
                if (value == "head")
                    US_COLOR = Colors.Yellow;
                else if (value == "leader")
                    US_COLOR = Colors.Red;
                else
                    US_COLOR = Colors.Transparent;
            }
        }
        public string US_PATH { get; set; }
        public string US_LOGIN { get; set; }
        public string US_PASSWORD { get; set; }
        public decimal US_BALANCE { get; set; }
        public Nullable<short> US_LEVEL { get; set; }
        public Nullable<int> US_GUILD_ID { get; set; }
    
        public virtual GUILD GUILD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK_MEMBER> TASK_MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_ARSENAL> USER_ARSENAL { get; set; }
    }
}
