//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEAPON_DICTIONARY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WEAPON_DICTIONARY()
        {
            this.USER_ARSENAL = new HashSet<USER_ARSENAL>();
        }
    
        public int WEAPON_ID { get; set; }
        public string WEAPON_NAME { get; set; }
        public string WEAPON_TYPE_NAME { get; set; }
        public decimal WEAPON_WEIGHT { get; set; }
        public Nullable<int> WEAPON_MORTALITY { get; set; }
        public string WEAPON_IMAGE { get; set; }
        public string WEAPON_DESCRIPTION { get; set; }
        public decimal WEAPON_VALUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_ARSENAL> USER_ARSENAL { get; set; }
    }
}
